## Pandas
*Pandas is an Open source ,BSD licenced library providing:
 1. High Performance
 2. Easy to use Data Structures
 3. Data Analysis tools for Python

#Data Frame and Data series
1. If Data is having more than one column then it is Dataframe with Row indexes and column names
2. Data with  less than one column (that means only rows) or only one column(and atlest 1 row ) called series


In [5]:
import pandas as pd
import numpy as np

In [6]:
#Creating Data Frame
#arguments needed: 1 array/numpy array),index(Row indexes),columns=(columnnames)
list1=list(range(1,21))
arr=np.array(list1)
df=pd.DataFrame(arr.reshape(5,4),index=['R1','R2','R3','R4','R5'],columns=['C1','C2','C3','C4'])
print('numpy array')
print(arr)
print('Dataframe')
print(df)
#Creating DataFrame


numpy array
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Dataframe
    C1  C2  C3  C4
R1   1   2   3   4
R2   5   6   7   8
R3   9  10  11  12
R4  13  14  15  16
R5  17  18  19  20


In [7]:
#dataframe conversion to csv and will stored the folder notebook present
df.to_csv('t1.csv')

In [8]:
#accessing columns
df.loc['R1','C1'] #got value in C1 column value in R1 row
df.loc[:,'C1'] #all rows of C1 column
#whenever there is one or less than one column result will be series else it will be dataframe

R1     1
R2     5
R3     9
R4    13
R5    17
Name: C1, dtype: int32

In [9]:
type(df.loc['R1'])


pandas.core.series.Series

In [10]:
type(df.loc[:,'C1'])

pandas.core.series.Series

In [11]:
df.iloc[:,] #returning all columns all rows


C1  C2  C3  C4
R1   1   2   3   4
R2   5   6   7   8
R3   9  10  11  12
R4  13  14  15  16
R5  17  18  19  20

In [12]:
type(df.iloc[:,]) #more than one column returns dataframe

pandas.core.frame.DataFrame

In [13]:
#To select speific rows and columns
df.iloc[:3,:4] # return 3 rows 4 columns

C1  C2  C3  C4
R1   1   2   3   4
R2   5   6   7   8
R3   9  10  11  12

In [14]:
#convert dataframe to array
df.iloc[:,:].values 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [15]:
type(df.iloc[:,:].values) # generating numpy array

numpy.ndarray

In [16]:
df.iloc[:,:].values.shape # @D array with 5 rows 4 columns

(5, 4)

In [17]:
#Null check condition
df.isnull().sum()

C1    0
C2    0
C3    0
C4    0
dtype: int64

In [18]:
# if we want to check any duplicate value present in any column
#we will check valuecount if its equal to 1 no duplicates
df['C1'].value_counts() #no dupicate present

C1
1     1
5     1
9     1
13    1
17    1
Name: count, dtype: int64

In [19]:
#to get column's unique values #only works for column because rows are indexes
df['C1'].unique()

array([ 1,  5,  9, 13, 17])

In [20]:
#reading csv file
merc_data=pd.read_csv('merc.csv')
merc_data

Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
0            Kia       Rio  2020          4.2    Diesel          Manual   
1      Chevrolet    Malibu  2012          2.0    Hybrid       Automatic   
2       Mercedes       GLA  2020          4.2    Diesel       Automatic   
3           Audi        Q5  2023          2.0  Electric          Manual   
4     Volkswagen      Golf  2003          2.6    Hybrid  Semi-Automatic   
...          ...       ...   ...          ...       ...             ...   
9995         Kia    Optima  2004          3.7    Diesel  Semi-Automatic   
9996   Chevrolet    Impala  2002          1.4  Electric       Automatic   
9997         BMW  3 Series  2010          3.0    Petrol       Automatic   
9998        Ford  Explorer  2002          1.4    Hybrid       Automatic   
9999  Volkswagen    Tiguan  2001          2.1    Diesel          Manual   

      Mileage  Doors  Owner_Count  Price  
0      289944      3            5   8501  
1        5356      2            3  12092  
2      231440      4            2  11171  
3      160971      2            1  11780  
4      286618      3            3   2867  
...       ...    ...          ...    ...  
9995     5794      2            4   8884  
9996   168000      2            1   6240  
9997    86664      5            1   9866  
9998   225772      4            1   4084  
9999   157882      3            3   3342  

[10000 rows x 10 columns]

In [21]:
#top 5 rows
merc_data.head()

Brand   Model  Year  Engine_Size Fuel_Type    Transmission  Mileage  \
0         Kia     Rio  2020          4.2    Diesel          Manual   289944   
1   Chevrolet  Malibu  2012          2.0    Hybrid       Automatic     5356   
2    Mercedes     GLA  2020          4.2    Diesel       Automatic   231440   
3        Audi      Q5  2023          2.0  Electric          Manual   160971   
4  Volkswagen    Golf  2003          2.6    Hybrid  Semi-Automatic   286618   

   Doors  Owner_Count  Price  
0      3            5   8501  
1      2            3  12092  
2      4            2  11171  
3      2            1  11780  
4      3            3   2867

In [22]:
#last 5 rows
merc_data.tail()

Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
9995         Kia    Optima  2004          3.7    Diesel  Semi-Automatic   
9996   Chevrolet    Impala  2002          1.4  Electric       Automatic   
9997         BMW  3 Series  2010          3.0    Petrol       Automatic   
9998        Ford  Explorer  2002          1.4    Hybrid       Automatic   
9999  Volkswagen    Tiguan  2001          2.1    Diesel          Manual   

      Mileage  Doors  Owner_Count  Price  
9995     5794      2            4   8884  
9996   168000      2            1   6240  
9997    86664      5            1   9866  
9998   225772      4            1   4084  
9999   157882      3            3   3342

In [23]:
#specific number of first and last rows
merc_data.head(10)

Brand     Model  Year  Engine_Size Fuel_Type    Transmission  Mileage  \
0         Kia       Rio  2020          4.2    Diesel          Manual   289944   
1   Chevrolet    Malibu  2012          2.0    Hybrid       Automatic     5356   
2    Mercedes       GLA  2020          4.2    Diesel       Automatic   231440   
3        Audi        Q5  2023          2.0  Electric          Manual   160971   
4  Volkswagen      Golf  2003          2.6    Hybrid  Semi-Automatic   286618   
5      Toyota     Camry  2007          2.7    Petrol       Automatic   157889   
6       Honda     Civic  2010          3.4  Electric       Automatic   139584   
7         Kia  Sportage  2001          4.7  Electric  Semi-Automatic   157495   
8         Kia  Sportage  2014          2.6    Hybrid          Manual    98700   
9      Toyota      RAV4  2005          3.1    Petrol          Manual   107724   

   Doors  Owner_Count  Price  
0      3            5   8501  
1      2            3  12092  
2      4            2  11171  
3      2            1  11780  
4      3            3   2867  
5      4            4   7242  
6      3            1  11208  
7      2            2   7950  
8      3            4   9926  
9      2            5   6545

In [24]:
merc_data.tail(10)

Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
9990        Audi        A3  2019          1.8  Electric          Manual   
9991    Mercedes   E-Class  2017          1.1    Diesel       Automatic   
9992         BMW  5 Series  2016          1.2    Hybrid       Automatic   
9993       Honda    Accord  2019          4.7    Hybrid  Semi-Automatic   
9994       Honda     Civic  2016          2.9    Petrol          Manual   
9995         Kia    Optima  2004          3.7    Diesel  Semi-Automatic   
9996   Chevrolet    Impala  2002          1.4  Electric       Automatic   
9997         BMW  3 Series  2010          3.0    Petrol       Automatic   
9998        Ford  Explorer  2002          1.4    Hybrid       Automatic   
9999  Volkswagen    Tiguan  2001          2.1    Diesel          Manual   

      Mileage  Doors  Owner_Count  Price  
9990    85496      4            3  11890  
9991   179286      5            1   8214  
9992    13386      3            5  12332  
9993   155874      4            3  12382  
9994   255889      2            2   6682  
9995     5794      2            4   8884  
9996   168000      2            1   6240  
9997    86664      5            1   9866  
9998   225772      4            1   4084  
9999   157882      3            3   3342

In [25]:
#standard info 
merc_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Brand         10000 non-null  object 
 1   Model         10000 non-null  object 
 2   Year          10000 non-null  int64  
 3   Engine_Size   10000 non-null  float64
 4   Fuel_Type     10000 non-null  object 
 5   Transmission  10000 non-null  object 
 6   Mileage       10000 non-null  int64  
 7   Doors         10000 non-null  int64  
 8   Owner_Count   10000 non-null  int64  
 9   Price         10000 non-null  int64  
dtypes: float64(1), int64(5), object(4)
memory usage: 781.4+ KB


In [26]:
#statstical info this consider only integer and floating point features
merc_data.describe()

Year   Engine_Size        Mileage         Doors   Owner_Count  \
count  10000.000000  10000.000000   10000.000000  10000.000000  10000.000000   
mean    2011.543700      3.000560  149239.111800      3.497100      2.991100   
std        6.897699      1.149324   86322.348957      1.110097      1.422682   
min     2000.000000      1.000000      25.000000      2.000000      1.000000   
25%     2006.000000      2.000000   74649.250000      3.000000      2.000000   
50%     2012.000000      3.000000  149587.000000      3.000000      3.000000   
75%     2017.000000      4.000000  223577.500000      4.000000      4.000000   
max     2023.000000      5.000000  299947.000000      5.000000      5.000000   

             Price  
count  10000.00000  
mean    8852.96440  
std     3112.59681  
min     2000.00000  
25%     6646.00000  
50%     8858.50000  
75%    11086.50000  
max    18301.00000

In [27]:
#if csv file has ; as separator instead of '
pd.read_csv('t2.csv',sep=';')  #sep attribute is required

C1  C2  C3  C4
R1   1   2   3   4
R2   5   6   7   8
R3   9  10  11  12
R4  13  14  15  16
R5  17  18  19  20

**if my data in file  is like**
testfile=
('col1,col2,col3,\n',
'x,y,z,1\n',
'a,b,c,2,\n')
  -To read this pd.read_csv(StringIO('testfile.csv'))

In [77]:
#way to read data from csv(another kind)
import pandas as pd
from io import StringIO
df=pd.read_csv(io.StringIO('test.csv').getvalue())
print(df)



  col1 col2  col3   \n 
0    x    y     1   \n 
1    a    b     2   \n 
